<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>.\assets\CloudLens.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudLens.Core\CloudLens.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\CloudLens.ico" />
  </ItemGroup>

</Project>
